spring:
  application:
    name: volunteeros
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  cache:
    type: redis

  threads:
    virtual:
      enabled: true

  ai:
    google:
      genai:
        api-key: ${AI_API}
        chat:
          options:
            model: gemini-2.5-flash

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}

  elasticsearch:
    uris: ${ELASTICSEARCH_URI}

logging:
  file:
    name: logs/log.log
  level:
    root: ${LOG_LEVEL}

server:
  port: ${SERVER_PORT}

security:
  csrf-enabled: false

jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}

  access-expiration:  ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
